# Generated by Django 2.1.5 on 2019-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyone',
            field=models.IntegerField(default='777'),
        ),
    ]
